import { flatten, oklchToHex, oklchToHslChannels, parseOklch, type Oklch } from './color';
import { layoutVariables, THEME_BRIDGE } from './layout';
import { TOKENS } from './tokens';
import { paletteOf, type Theme } from './theme';

export const FORMAT_IDS = [
	'tailwind-v4',
	'preset-class',
	'tailwind-v3',
	'css-vars',
	'registry-json',
	'ts-module'
] as const;

export type FormatId = (typeof FORMAT_IDS)[number];

export interface ExportOptions {
	/** `hex` is for hosts that still run through a colour library which cannot read OKLCH. */
	colorSpace: 'oklch' | 'hex';
	/** `success` and `warning` are not part of shadcn's set; a host that never uses them can drop them. */
	includeExtras: boolean;
	/**
	 * Adds a README next to the files.
	 *
	 * Worth having when the export is handed to someone else or to an agent: the instructions
	 * otherwise live in this app's UI, which the person opening the folder is not looking at.
	 */
	includeReadme: boolean;
}

export const DEFAULT_OPTIONS: ExportOptions = {
	colorSpace: 'oklch',
	includeExtras: true,
	includeReadme: false
};

export interface ExportFile {
	/** Relative to whichever directory the user exports into. */
	path: string;
	language: 'css' | 'ts' | 'json' | 'js' | 'md';
	contents: string;
}

export interface ExportFormat {
	id: FormatId;
	label: string;
	description: string;
	/** What to do with the files once they are written. Deliberately in English: it is developer
	 *  instruction that ends up pasted into issues and commit messages. */
	usage: string;
	build(theme: Theme, options: ExportOptions): ExportFile[];
}

const BANNER = 'Generated by OpenThemeGenerator. Edit the theme, not this file.';

function emitted(options: ExportOptions): readonly string[] {
	return TOKENS.filter((token) => options.includeExtras || token.core).map((token) => token.name);
}

function read(value: string): Oklch {
	return parseOklch(value) ?? { l: 0.5, c: 0, h: 0, alpha: 1 };
}

function render(value: string, options: ExportOptions): string {
	return options.colorSpace === 'hex' ? oklchToHex(read(value)) : value;
}

/** The semantic icon colours are colours, not geometry, so they honour the colour-space choice. */
function isColorVariable(name: string): boolean {
	return name.startsWith('icon-');
}

/**
 * A layout variable as the target should read it. Geometry passes through; the icon colours follow
 * the chosen colour space; and the shadows — which carry a colour inside a longer value — are
 * re-spelled as `rgba` whenever the host was promised no OKLCH.
 */
function paint(name: string, value: string, options: ExportOptions): string {
	if (isColorVariable(name)) return render(value, options);
	return options.colorSpace === 'hex'
		? value.replace(/oklch\(0 0 0 \/ ([\d.]+)\)/g, 'rgba(0, 0, 0, $1)')
		: value;
}

/**
 * Geometry first, then colour. The two are written into the same block on purpose: a host that
 * switches themes at runtime has to switch both, and splitting them across two selectors is how
 * a theme ends up half applied.
 *
 * In dark mode only the shadows change, but they are re-emitted rather than inherited — a `.dark`
 * block that carries some of the layout and not the rest is harder to read than one that repeats.
 */
function declarations(
	theme: Theme,
	mode: 'light' | 'dark',
	options: ExportOptions,
	indent: string
): string {
	const palette = paletteOf(theme, mode);
	const layout =
		mode === 'light'
			? Object.entries(layoutVariables(theme.layout, mode))
			: Object.entries(layoutVariables(theme.layout, mode)).filter(([name]) =>
					name.startsWith('elevation-')
				);

	return [
		...layout.map(([name, value]) => `${indent}--${name}: ${paint(name, value, options)};`),
		...emitted(options).map(
			(token) => `${indent}--${token}: ${render(palette[token] ?? '', options)};`
		)
	].join('\n');
}

/**
 * Alpha cannot survive a split into channels, so a translucent token is composited first. The
 * layout variables are written as they are — only the colours are channel-split, because only
 * colours go through `hsl(var(--token))`.
 */
function hslDeclarations(theme: Theme, mode: 'light' | 'dark', options: ExportOptions): string {
	const palette = paletteOf(theme, mode);
	const backdrop = read(palette.background ?? 'oklch(1 0 0)');
	const layout =
		mode === 'light'
			? Object.entries(layoutVariables(theme.layout, mode))
			: Object.entries(layoutVariables(theme.layout, mode)).filter(([name]) =>
					name.startsWith('elevation-')
				);

	// A v3-era project predates oklch(), and unlike the colour tokens these are consumed whole
	// rather than through hsl(var(--token)) — so they are written as hex and rgba regardless of
	// what colour space was asked for.
	const flat: ExportOptions = { ...options, colorSpace: 'hex' };

	return [
		...layout.map(([name, value]) => `    --${name}: ${paint(name, value, flat)};`),
		...emitted(options).map(
			(token) =>
				`    --${token}: ${oklchToHslChannels(flatten(read(palette[token] ?? ''), backdrop))};`
		)
	].join('\n');
}

const tailwindV4: ExportFormat = {
	id: 'tailwind-v4',
	label: 'Tailwind v4 + shadcn',
	description:
		'The whole app.css: colour and layout tokens on :root and .dark, plus the @theme inline block that wires them into the spacing, text, radius and shadow scales.',
	usage:
		'Replace src/app.css with this file, or paste the :root, .dark and @theme inline blocks over the ones already there. The utility names stay the same — but p-4, text-base and shadow-sm now follow the theme rather than the framework defaults, so a density change moves the whole app.',
	build: (theme, options) => [
		{
			path: 'app.css',
			language: 'css',
			contents: `/* ${theme.name} — ${BANNER} */
@import 'tailwindcss';

@custom-variant dark (&:is(.dark *));

:root {
${declarations(theme, 'light', options, '\t')}
}

.dark {
${declarations(theme, 'dark', options, '\t')}
}

/* The source variables above and the scale names below are deliberately different: a theme
   variable that reads its own name — --spacing: var(--spacing) — is a cycle, not a mapping. */
@theme inline {
	--radius-sm: calc(var(--radius) - 4px);
	--radius-md: calc(var(--radius) - 2px);
	--radius-lg: var(--radius);
	--radius-xl: calc(var(--radius) + 4px);
${THEME_BRIDGE.map((entry) => `\t--${entry.theme}: var(--${entry.source});`).join('\n')}
${emitted(options)
	.map((token) => `\t--color-${token}: var(--${token});`)
	.join('\n')}
}

@layer base {
	* {
		@apply border-border outline-ring/50;
	}

	body {
		@apply bg-background text-foreground;
	}
}
`
		}
	]
};

const presetClass: ExportFormat = {
	id: 'preset-class',
	label: 'Preset class',
	description:
		'One switchable block for a themes.css that already holds others. Toggle theme-<id> on <html> to apply it.',
	usage:
		'Append the file to src/themes.css, import that from app.css, and toggle the class on document.documentElement. Suppress transitions across the swap or Chromium keeps painting the old colours.',
	build: (theme, options) => [
		{
			path: `themes/${theme.id}.css`,
			language: 'css',
			contents: `/* ${theme.name} — ${BANNER}
 *
 * Light and dark are a separate axis: \`.dark\` and \`.theme-${theme.id}\` both sit on <html>, so the
 * dark half is written as \`.dark.theme-${theme.id}\` rather than nested inside it.
 *
 * Both selectors are anchored to \`:root\`. A bare \`.theme-${theme.id}\` carries the same specificity
 * as the \`:root\` block your app.css already declares, so source order would decide and importing
 * this file first would change nothing.
 */

:root.theme-${theme.id} {
${declarations(theme, 'light', options, '\t')}
}

:root.dark.theme-${theme.id} {
${declarations(theme, 'dark', options, '\t')}
}
`
		}
	]
};

const tailwindV3: ExportFormat = {
	id: 'tailwind-v3',
	label: 'Tailwind v3 + shadcn',
	description:
		'HSL channels in globals.css and the matching tailwind.config.js extension, for projects still on v3.',
	usage:
		'Drop globals.css in and merge the colors and borderRadius blocks into the existing tailwind.config.js. Translucent tokens were composited over the background: v3 cannot carry an alpha inside hsl(var(--token)).',
	build: (theme, options) => [
		{
			path: 'globals.css',
			language: 'css',
			contents: `/* ${theme.name} — ${BANNER} */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${hslDeclarations(theme, 'light', options)}
  }

  .dark {
${hslDeclarations(theme, 'dark', options)}
  }
}

@layer base {
  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground;
  }
}
`
		},
		{
			path: 'tailwind.config.js',
			language: 'js',
			contents: `// ${theme.name} — ${BANNER}
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx,js,jsx,svelte,vue,html}'],
  theme: {
    extend: {
      colors: {
${emitted(options)
	.map((token) => `        '${token}': 'hsl(var(--${token}))'`)
	.join(',\n')}
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)'
      }
    }
  },
  plugins: []
};
`
		}
	]
};

const cssVars: ExportFormat = {
	id: 'css-vars',
	label: 'Plain CSS variables',
	description:
		'No framework at all. Follows the system by default, and data-theme on <html> overrides it in either direction.',
	usage:
		'Link it before your own stylesheet and read the tokens with var(--background). reference/ in this repository is a page built on exactly this file.',
	build: (theme, options) => [
		{
			path: 'theme.css',
			language: 'css',
			contents: `/* ${theme.name} — ${BANNER}
 *
 * Three states, not two: an explicit choice sets data-theme on <html>, and with no choice made the
 * media query decides. The dark block is guarded so that a page pinned to light stays light even
 * on a machine that prefers dark.
 */

:root {
${declarations(theme, 'light', options, '\t')}
}

@media (prefers-color-scheme: dark) {
	:root:not([data-theme='light']) {
${declarations(theme, 'dark', options, '\t\t')}
	}
}

:root[data-theme='dark'] {
${declarations(theme, 'dark', options, '\t')}
}
`
		}
	]
};

const registryJson: ExportFormat = {
	id: 'registry-json',
	label: 'shadcn registry item',
	description:
		'The JSON shape `npx shadcn@latest add <url>` reads, so the theme can be installed rather than pasted.',
	usage:
		'Serve the file over HTTP and run `npx shadcn@latest add <url>`. Works for shadcn/ui and shadcn-svelte, which read the same registry item.',
	build: (theme, options) => {
		const forMode = (mode: 'light' | 'dark') => {
			const palette = paletteOf(theme, mode);
			const shadows = Object.entries(layoutVariables(theme.layout, mode)).filter(([name]) =>
				name.startsWith('elevation-')
			);
			return {
				...Object.fromEntries(shadows),
				...Object.fromEntries(
					emitted(options).map((token) => [token, render(palette[token] ?? '', options)])
				)
			};
		};

		// The registry's `theme` bucket is for values that do not change with the mode, which is
		// exactly the geometry; the shadows differ per mode and ride along with the palettes.
		const geometry = Object.fromEntries(
			Object.entries(layoutVariables(theme.layout, 'light')).filter(
				([name]) => !name.startsWith('elevation-')
			)
		);

		return [
			{
				path: `${theme.id}.json`,
				language: 'json',
				contents: `${JSON.stringify(
					{
						$schema: 'https://ui.shadcn.com/schema/registry-item.json',
						name: theme.id,
						type: 'registry:theme',
						title: theme.name,
						description: theme.description,
						cssVars: {
							theme: geometry,
							light: forMode('light'),
							dark: forMode('dark')
						}
					},
					null,
					2
				)}\n`
			}
		];
	}
};

const tsModule: ExportFormat = {
	id: 'ts-module',
	label: 'TypeScript module',
	description:
		'The theme as data plus a short apply function, for anything that sets its own colours and metrics from script.',
	usage:
		'Import it and call applyTheme(document.documentElement, mode). Both objects are plain data, so a canvas, a chart library or a native shell can read the same values the CSS does.',
	build: (theme, options) => {
		const entries = (mode: 'light' | 'dark') => {
			const palette = paletteOf(theme, mode);
			return [
				...Object.entries(layoutVariables(theme.layout, mode))
					.filter(([name]) => name.startsWith('elevation-'))
					.map(([name, value]) => `\t\t'${name}': '${value}'`),
				...emitted(options).map(
					(token) => `\t\t'${token}': '${render(palette[token] ?? '', options)}'`
				)
			].join(',\n');
		};

		const geometry = Object.entries(layoutVariables(theme.layout, 'light'))
			.filter(([name]) => !name.startsWith('elevation-'))
			.map(([name, value]) => `\t\t'${name}': '${value}'`)
			.join(',\n');

		return [
			{
				path: `${theme.id}.ts`,
				language: 'ts',
				contents: `// ${theme.name} — ${BANNER}

export const ${camel(theme.id)} = {
	id: '${theme.id}',
	name: ${JSON.stringify(theme.name)},
	/** Geometry, which does not change with the mode. */
	layout: {
${geometry}
	},
	light: {
${entries('light')}
	},
	dark: {
${entries('dark')}
	}
} as const;

export type Mode = 'light' | 'dark';

/** Writes the theme onto an element as custom properties. Pass document.documentElement for the page. */
export function applyTheme(target: HTMLElement, mode: Mode): void {
	const declared = { ...${camel(theme.id)}.layout, ...${camel(theme.id)}[mode] };
	for (const [token, value] of Object.entries(declared)) {
		target.style.setProperty(\`--\${token}\`, value);
	}
}
`
			}
		];
	}
};

function camel(id: string): string {
	return id.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

export const FORMATS: readonly ExportFormat[] = [
	tailwindV4,
	presetClass,
	tailwindV3,
	cssVars,
	registryJson,
	tsModule
];

export function formatById(id: FormatId): ExportFormat {
	return FORMATS.find((format) => format.id === id) ?? tailwindV4;
}

/**
 * The README that ships beside the files.
 *
 * Addressed to whoever opens the folder — a colleague or a coding agent — rather than to the
 * person who pressed export, because they are the one who no longer has this app in front of them.
 */
function readme(format: ExportFormat, theme: Theme, files: ExportFile[]): ExportFile {
	const layout = layoutVariables(theme.layout, 'light');

	return {
		path: 'README.md',
		language: 'md',
		contents: `# ${theme.name}

${theme.description}

${BANNER}

## Files

${files.map((file) => `- \`${file.path}\` — ${file.language}`).join('\n')}

## Installing

${format.usage}

## What this theme decides

| | |
| --- | --- |
| Sidebar design | ${theme.layout.sidebarStyle} |
| Density | ${theme.layout.density} |
| Corner radius | ${layout.radius} |
| Border width | ${layout['border-width']} |
| Elevation | ${theme.layout.elevation} |
| Sidebar width | ${layout['sidebar-width']} expanded, ${layout['sidebar-width-icon']} collapsed |
| Content width | ${layout['container-max']} |

Colours are OKLCH${theme.light.background?.includes('#') ? ' (exported as hex)' : ''}. Light values
live on \`:root\`, dark values on \`.dark\` — both are complete palettes rather than one derived from
the other, so editing one never silently changes the other.

## Conventions worth keeping

- Read colours through the tokens (\`var(--background)\`, \`bg-background\`), never as literals. That
  is what makes the theme swappable at all.
- \`--sidebar-width\` and \`--sidebar-width-icon\` are the names shadcn's own sidebar component reads,
  so its collapse behaviour follows this file without further wiring.
- The \`--icon-*\` values are semantic sidebar icon colours; \`--sidebar-icon-uses-system\` is \`1\` when
  the theme wants them and \`0\` when icons should inherit the text colour.
`
	};
}

export function buildExport(id: FormatId, theme: Theme, options: ExportOptions): ExportFile[] {
	const format = formatById(id);
	const files = format.build(theme, options);
	return options.includeReadme ? [...files, readme(format, theme, files)] : files;
}
